### ISSUE TITLE
No size limiting on backend side.

### ISSUE THREAD

**Issue by iczelia** [kubasiatkowski/funkypass#6]
While frontend is keeping you away from entering Int32.MAX_VALUE to minimum field, backend doesn't.
This allowed me to do such thing:
![obraz](https://user-images.githubusercontent.com/27734421/54863880-92f79e00-4d4e-11e9-9cd1-4e1c7b4e21ac.png)
And, such thing:
![obraz](https://user-images.githubusercontent.com/27734421/54863881-9854e880-4d4e-11e9-89f0-304906b1e72a.png)
It needs to be fixed as fast as possible.

**Comment by kubasiatkowski** [comment]
It is not an issue because back end still can generate passwords of this length without throwing an error.
Limit in http front end was put due to issues with rendering and there is no reason to artificially reduce API functionality. Generation of long passwords takes significant  amount of time but it's up to consumer to decide if waiting is accepted.
